spring:
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181
      discovery:
        instance-id: c1
    config:
      server:
        git:
          uri: https://gitee.com/mk2021/domo-configuration
          username: 2576731178@qq.com
          password: Lee@gitee03
  application:
    name: config
  rabbitmq:
    port: 5672
    host: 192.168.3.102
    username: rabbit
    password: rabbit
# 打印所有地址
management:
  endpoints:
    web:
      exposure:
        include: '*'